### ISSUE TITLE
Using table inside of flexible content

### ISSUE THREAD

**Issue by Oli120495** [johannheyne/acf-table-field-pro-support#4]
v1.1.1

I've been using the free version of the table plugin on a website for quite some time now. Recently I have upgraded to the paid version, but replacing the old table fields within a flexible content area has caused the table pro fields to stop working, and generate a lot of console logs.

I've tested the table pro field inside a standard template and the fields are working correctly.

The structure for the flexible content are the table is in is as follow:
Top level Block > Group > Repeater > Table Field

Example of broken field (the table field specifically)
![image](https://github.com/johannheyne/acf-table-field-pro-support/assets/60880907/f9c2575e-0d74-40ec-89f5-f6a35feb305e)

Example of console logs for broken field
![image](https://github.com/johannheyne/acf-table-field-pro-support/assets/60880907/53d75be4-70b7-48e4-97e9-e238a12b2e9e)

**Comment by johannheyne** [comment]
Hi,

the free and the pro versions are not yet compatible. So you cant change the field type from free to pro. I guess I forgot to mention this on the website.
But I think it would actually be a good thing if this were possible. I'm working on a solution and will get back to you within 24 hours to see if it can be implemented in the short term.

Thanks for reporting me that issue,
Johann

-- 
Johann Heyne, Web-Developer
+49 (0)351 6465728
***@***.***
Dresden, Germany

**Comment by johannheyne** [comment]
With the next release next week it will be possible to switch from Table field type to Table Pro.

Cheers,
Johann

**Comment by johannheyne** [comment]
With the new version 1.2.0, you can now change an existing field
with field type "Table" (free version) to field type "Table Pro".

**Comment by Oli120495** [comment]
Hi Johann,

Really appreciate the quick response and rollout. I have updated the plugin, and the field is no longer broken, and I can see the data in there.

Unfortunately I am unable to actually change any of that data, or make any edits within those tables. Would you be able to look into this for me please? If its something insurmountable please let me know so I can start planning around it.

Thanks,

Ollie

**Comment by johannheyne** [comment]
I apologize for the inconvenience. I didn't notice this issue. The new version 1.2.1 should fix this issue.

Johann

**Comment by johannheyne** [comment]
If the error persists, please try clearing your browser's cache.

**Comment by Oli120495** [comment]
Hi Johann,

Appreciate the quick response as always. I have installed the update, turned off caching on the site, and cleared the browser cache.

I can manipulate all the columns and rows, create spans etc, but I still cannot edit the actual text inside the cells, the blue box that would typically appear is not coming up for me.

Thanks,

Ollie

**Comment by johannheyne** [comment]
You may have already saved the field with the missing content type setting which was my fault. The solution would be to change the content type for the table to "Editor" and back to "Simple Text". This could fix it for your situation.

https://github.com/johannheyne/acf-table-field-pro-support/assets/621710/bd500ab1-ab52-4253-a521-ae98bad4af26

**Comment by Oli120495** [comment]
Thats resolved the issue.

Thank you very much for all of your help, and fast responses.

Ollie
